language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - CONFIG=""
  - CONFIG="--enable-assertions"
  - CONFIG="--enable-fixed-point"
  - CONFIG="--enable-fixed-point --disable-float-api"
  - CONFIG="--enable-fixed-point --enable-assertions"

script:
  - ./autogen.sh
  - ./configure $CONFIG
  - make distcheck

matrix:
  exclude:
    - compiler: gcc
      os: osx

before_install:
  - git clone https://github.com/berkus/travis-scripts.git travis-ci
  - ./travis-ci/travis_install_packages.sh

install:
  - mkdir -p _build_
  - cd _build_
  - cmake -GUnix\ Makefiles -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - make -j4
  - cd ..

script:
  - cd _build_/tests
  - ctest -V
  - cd ../..

branches:
  only:
    - master

notifications:
  recipients:
    - berkus@metta.systems
  email:
    on_success: change
    on_failure: always

